---
title: "BIOS 451: Christiana's Dashboard"
format: dashboard
editor: visual
---

## Libraries

```{r}
#| context: setup
library(nhanesA)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

## Load NHANES Dataset

```{r load NHANES}

nh_raw <- nhanesFromURL("https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2017/DataFiles/P_HIQ.xpt") |>
  full_join(nhanesFromURL("https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2017/DataFiles/P_INQ.xpt")) |>
  full_join(nhanesFromURL("https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2017/DataFiles/P_HUQ.xpt")) |>
  full_join(nhanesFromURL("https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2017/DataFiles/P_DEMO.xpt")) |>
  select(RIAGENDR, RIDAGEYR, RIDRETH3, HUQ010, HUQ030, INDFMMPI, INDFMMPC, HIQ011)
```

## Recode & Rename Variables

```{r recode & rename}
nh <- nh_raw |>
  mutate(across(where(is.character),as.factor)) |>
  filter(RIDAGEYR >= 18 & RIDAGEYR <= 25) |>
  rename(
    sex = RIAGENDR,
    age = RIDAGEYR,
    ethn = RIDRETH3,
    fmpli = INDFMMPI,
    fmplc = INDFMMPC,
    health_con = HUQ010,
    routine_place = HUQ030,
    ins_cov = HIQ011)

```

# Plot 1

```{r plot 1}

nh |> 
  ggplot(mapping = aes(x = ins_cov, fill = routine_place)) +
  geom_bar(position = "fill") +
  facet_wrap(~sex) +
  labs(title = "Routine Healthcare Access by Insurance Coverage, Ages 18-25",
    x = "Insurance Coverage", 
    y = "% w/ a Routine Place to go for Healthcare",
    subtitle = "n = 1,039",
    fill = "Routine Place") +
  theme_bw() +
  scale_x_discrete(limits = c("Yes", "No")) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(name = "Routine Place",
                    values = c("Yes" = "#8EE8D8", 
                               "There is no place" = "#00BDB6",
                               "There is more than one place" = "#133844"),
                    labels = c("Yes" = "One place",
                               "There is no place" = "No place",
                               "There is more than one place" = "Multiple places"),
                    guide = guide_legend(direction = "vertical",
                         title.position = "top",
                         label.position = "right")) +
  theme(
    text = element_text(family = "GillSans", size = 16),
    axis.text = element_text(size = 14),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5))

```

# Plot 2

```{r plot 2}

# create age groups & drop NAs
nh <- nh |>
  mutate(age_group = cut(age,
    breaks = c(18, 20, 22, 25),
    labels = c("18-19", "20-21", "22-25"),
    right = TRUE)) |>
  filter(!is.na(age_group))

# filter dont knows from ins_cov
nh <- nh |>
  filter(ins_cov != "Don't know")

nh |>
  ggplot(mapping = aes(x = age_group, fill = routine_place)) +
  geom_bar(position = "dodge") +
  facet_wrap(~ins_cov) +
  labs(
    title = "Routine Place for Healthcare by Age Group (18-25)",
    subtitle = "Faceted by Insurance Coverage",
    x = "Age Groups (years)",
    y = "# of Respondents",
    fill = "Routine Place") +
  scale_fill_manual(
  values = c(
    "Yes" = "#8EE8D8",
    "There is no place" = "#00BDB6",
    "There is more than one place" = "#133844"),
  labels = c(
    "Yes" = "One place",
    "There is no place" = "No place",
    "There is more than one place" = "Multiple places"),
  name = "Routine Place") +
  theme_bw(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 0, vjust = 0.5),
    legend.position = c(0.2,0.7),
    text = element_text(family = "GillSans", size = 17),
    plot.title = element_text(hjust = 0.5, size = 17),
    plot.subtitle = element_text(hjust = 0.5, size = 14))

```
